version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # We don't pin most of our patched gems as plenty of people might need old(er) versions
      - dependency-name: "capybara"
      - dependency-name: "cucumber"
      - dependency-name: "selenium-webdriver"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
