inherit_gem:
  citizens-advice-style:
    - default.yml

AllCops:
  Exclude:
    # This patch is 80% copied code from the upstream repo. As such there are different style
    - 'lib/automation_helpers/patches/parallel_cucumber.rb'
  SuggestExtensions: false
