require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  # Display all verbose info on failures to help people triage how to fix
  DisplayCopNames: true
  DisplayStyleGuide: true
  # Enable all NewCops by default (Even new 1.x cops)
  NewCops: enable
  # Target Ruby 3.0
  TargetRubyVersion: 3.0
  Exclude:
    # Remove vendor files from being checked
    - vendor/**/*

# This cop seems erroneous still
Gemspec/DevelopmentDependencies:
  Enabled: false

# We don't enable MFA yet on this repo
Gemspec/RequireMFA:
  Enabled: false

# We have a linelength of 140 characters across the codebase/s
Layout/LineLength:
  Max: 140
  Exclude:
    - ^Given
    - ^When
    - ^Then

Metrics/BlockLength:
  Exclude:
    # Specs deliberately will almost always break this cop (It should be added to rubocop-rspec defaults ideally)
    - spec/**/*

# This is a casting method which is in a catch-22 situation as it casts to a boolean, but it is in itself not really a boolean method
Naming/PredicateMethod:
  AllowedMethods:
    - to_bool

# Remove specs breaking the cop limit for large array/hash responses
RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']

# This is a single standardised transform
RSpec/SpecFilePathFormat:
  CustomTransform:
    WebDriver: webdriver

# Stylistic preference to make the RSpec tests flow better
RSpec/MessageSpies:
  EnforcedStyle: receive
